version: '1'
services:
  backend:
    image: python:3.11.4-alpine3.18
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  
  frontend:
    image: node:18.10
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run build --prod"
    ports:
      - "4200:4200"
