version: '1'
services:
  backend:
    image: python:3.9
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  
  frontend:
    image: node:14-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && ng serve --host 0.0.0.0"
    ports:
      - "4200:4200"
