# Generated by Django 4.2.4 on 2023-08-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksAdmin', '0003_alter_task_created_alter_task_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.CharField(blank=True, choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE')], default='DONE', max_length=20),
        ),
    ]
